# Generated by Django 4.1.5 on 2023-01-15 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.client'),
        ),
    ]
