# Generated by Django 4.1.5 on 2023-01-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='client',
        ),
        migrations.AddField(
            model_name='trip',
            name='client',
            field=models.ManyToManyField(to='trips.client'),
        ),
    ]
